### ISSUE TITLE
Skill level allow points for multiple categories frontend

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#164]
## Requirement
- https://github.com/IT-REX-Platform/content_service/issues/69

## Description
A lecturer must be able to choose and select multiple skill types for a piece of content.
Add point input to categories (low, medium, high) for easier usage.

## Acceptance Criteria
- [ ] UI changed

**Comment by v-morlock** [comment]
was mostly done in the last sprint
