### ISSUE TITLE
Bug: Courses which are not available (published & within start-end dates) are shown in course catalog

### ISSUE THREAD

**Issue by myluki2000** [IT-REX-Platform/gits-frontend#201]
For student that should not be the case, for lecturer that is desired

**Comment by v-morlock** [comment]
Eigentlich finde ich sowas sollte im backend gefiltert werden aber ich machs jetzt mal

**Comment by myluki2000** [comment]
> Eigentlich finde ich sowas sollte im backend gefiltert werden aber ich machs jetzt mal

Dafür gibt es das Filtering System im Backend, das du verwenden solltest
