### ISSUE TITLE
BUG: Fix inconsistent state after add/delete

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#206]
## Description
In a lot of places the page needs to be refreshed by the user in order to see the new values.

Places where it is needed (right now): 

- [x] after deleting invalid media
- [x] deleting content from a stage
- [x] when you added edited a quiz (add question) and change to the student view
- [ ] after completing a quiz (to update the progress/suggestions)
- [ ] When adding an existing quiz to a section it will only disappear from the "other contents" group on a forced page reload

Investigate other places & ask other devs/users where they encountered the same problem.

## Acceptance criteria
- [x] user does not need to refresh the page manually anymore

**Comment by v-morlock** [comment]
we can't really do anything about "after completing a quiz (to update the progress/suggestions)" in my opinion as this is calculated async by the backend, so how should we know about it. For the last, I don't even know how to reproduce this?  Other should be fixed
