### ISSUE TITLE
Frontend chapter bugs

### ISSUE THREAD

**Issue by PaulBredl** [IT-REX-Platform/gits-frontend#209]
## Description

![Image](https://user-images.githubusercontent.com/34026908/269438962-d38749b2-37fe-40e8-954c-a06a3c04314d.png)

- könnt ihr btw das default end date von einem chapter auf das ent date vom kurs setzen? sonst erstellt man als lecturer bestimmt versehentlich kapitel, die nur eine woche verfügbar sind

- Außerdem wenn ich ein Kapitel bearbeiten will, dass ich schon bearbeitet hab, werden die kompletten Daten resettet und da steht wieder "Chapter 1" und die anderen felder sind auch wieder die default werte (wenn man reloaded werden einem die geänderten Werte angezeigt)

- Die description eines chapters wird nicht angezeigt

- wenn man content löscht wird er trotzdem noch angezeigt, man muss reloaden

**Comment by v-morlock** [comment]
den ersten bug kann ich nicht reproduzieren

**Comment by PaulBredl** [comment]
@v-morlock ich probiers mal nochmal, vlt haben Robert und Marcel den schon gefixt
