### ISSUE TITLE
Frontend Bug quiz progress not tracked

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#221]
## Description
After doing a multiple choice quiz the following response is shown. Progress is therefore not tracked

![Image](https://github.com/IT-REX-Platform/gits-frontend/assets/49751191/074730d0-d4ab-4b09-a470-b076adf7e23f)

**Comment by PaulBredl** [comment]
I asked Valentin if I can merge the backend changes (regarding Quiz feedback issue) and he said yes he will do it on saturday, I guess he didnt

**Comment by PaulBredl** [comment]
this isnt really an issue if https://github.com/IT-REX-Platform/gits-frontend/issues/178 is done
