### ISSUE TITLE
Bug: Quiz in "other content" is null

### ISSUE THREAD

**Issue by SkyDiverStar** [IT-REX-Platform/gits-frontend#262]
In course "Test course 3" in chapter 1 in the "other content" bracket, the quizzes are still shown with those errors:

![Image](https://github.com/IT-REX-Platform/gits-frontend/assets/32335844/669f249a-52f8-4f8b-83e0-3de899357a58)

When checking in GraphiQL with the "findQuizzesByAssessmentIds" query, we get the following: 

![Image](https://github.com/IT-REX-Platform/gits-frontend/assets/32335844/36a0481c-da95-4049-934b-f0a6fb3ce4c9)

**Comment by PaulBredl** [comment]
done by @ZombieAlienRobot
