### ISSUE TITLE
Improve responsiveness

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#39]
## Description
The page should be able to adapt to smaller screens (only laptops, smartphones do not need to be fully supported)

## Acceptance Criteria

- [x] page works on small laptop screens

**Comment by SkyDiverStar** [comment]
Updated a few lines in the Navbar, index.tsx, join.tsx, course/create.tsx and course/id/index.tsx, to add more responsivness. In the home screen, the progress bars are being resized if the screen width hits certain breakpoints. 
Navbar course items might need a rework, meaning if the screen width falls under a certain breakpoint, secondary node might have to be displayed. Propably an abbreviation of the course name, but has to be discussed. 
Breakpoints are moistly the predefined ones from TailwindCSS and MUI.
As common screen widths I took following best practices:
- Desktop: 1280 x 720
- Tablet: 1280 x 800 or 768 x 1024
Everything above worked before, everything below those sizes are not accounted for.
