### ISSUE TITLE
Deployment to SQA server

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#4]
## Description
Figure out how to deploy all dockerfiles on the SQA K8s cluster and setup deployment.

## Acceptance Criteria
- [ ] services can be deployed to the cluster
- [ ] frontend can be deployed to the cluster
- [ ] documentation is updated with the new information

**Comment by v-morlock** [comment]
First version can be found here: https://github.com/IT-REX-Platform/gits-infra
